### ISSUE TITLE
Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed

### ISSUE THREAD

**Issue by jplew** [avivace/iosevka-docker#7]
Hi, I'm getting the following error when building a custom font with Docker:

```bash
Building process terminated.
Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
```

When I delete the ` capital-a = "straight-top-serifed"` line from my toml file, the build succeeds. I've included more detailed error logs below. I'm using WSL Ubuntu 14.

Here is the command I ran:
```
docker run -it -v $(pwd):/build avivace/iosevka-build contents::iosevka-custom
```

My `private-build-plans.toml`:

```
[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss10"

    [buildPlans.iosevka-custom.variants.design]
    capital-a = "straight-top-serifed"
    a = "double-storey"
    zero = "dotted"
    two = "curly-neck"

  [buildPlans.iosevka-custom.ligations]
  inherits = "fsharp"

[buildPlans.iosevka-custom.weights.light]
shape = 300
menu = 300
css = 300

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.medium]
shape = 500
menu = 500
css = 500

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"

  [buildPlans.iosevka-custom.slopes]
  upright = "normal"
  italic = "italic"
  ```

```bash
...
♦ Create TTF iosevka-custom-bolditalic -> dist/iosevka-custom/ttf-unhinted/iosevka-custom-bolditalic.ttf
♦ Create TTF iosevka-custom-light -> dist/iosevka-custom/ttf-unhinted/iosevka-custom-light.ttf
♦ Create TTF iosevka-custom-lightitalic -> dist/iosevka-custom/ttf-unhinted/iosevka-custom-lightitalic.ttf
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-italic.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-semibold.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-regular.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-mediumitalic.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-medium.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-semibolditalic.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-bold.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-light.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-bolditalic.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
× Error Unhandled exception when building "Builtin::File::dist/iosevka-custom/ttf-unhinted/iosevka-custom-lightitalic.ttf":
 Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
Building process terminated.
Error: Error: Composite {user} cannot be resolved: capital-a,straight-top-serifed.
    at Composite.decompose (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:157:19)
    at Composite.resolve (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:169:39)
    at Object.applyVariantData [as apply] (/tmp/build/Iosevka-5.2.1/font-src/support/variant-data.js:21:17)
    at reinit (/tmp/build/Iosevka-5.2.1/font-src/index.js:44:15)
    at main (/tmp/build/Iosevka-5.2.1/font-src/index.js:18:41)
    at ChildProcess.<anonymous> (/tmp/build/Iosevka-5.2.1/node_modules/verda/lib/actions/nodejs/command.js:53:31)
    at ChildProcess.emit (events.js:315:20)
    at emit (internal/child_process.js:903:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iosevka@5.2.1 build: `node utility/ensure-verda-exists && verda -f verdafile.js "contents::iosevka-custom"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iosevka@5.2.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-20T06_21_12_683Z-debug.log
```

**Comment by dehghani-mehdi** [comment]
It is not `iosevka-docker`'s fault, some of Iosevka's variant names have been changed in the recent versions, you should double-check them using the customizer (https://typeof.net/Iosevka/customizer).

Similar issue on the main repository -> https://github.com/be5invis/Iosevka/issues/760
